database:
  host: localhost
  port: 5050
  name: ccd_data
  username: ccd
  password: ccd
  driver: postgres
  sslmode: require
  batchSize: 100
  eventDataTable: event_data_report
period:
  startTime: "2022-01-01T07:00:00.000" # considered GMT
  endTime:   "2022-01-31T23:20:59.000"
worker:
  pool: 30 # Number of worker threads in the pool
rule:
  active: "staticfieldchange,arrayfieldchange,fieldchangecount"  # Active rules for event comparison
scan:
  jurisdiction: BEFTA_JURISDICTION_3  # Jurisdiction for scanning
  caseType: BEFTA_CASETYPE_3_1 # Case type for scanning
  caseId:
  maxEventProcessCount: 3000
  batchSize: 30
  concurrent:
    event:
      thresholdMilliseconds: 300000 # Threshold time in milliseconds for concurrent events. Set to -1 to disable threshold
  fieldChange:
    threshold: 25 # Threshold for field change detection
  report:
    enabled: true # Enable or disable report generation
    includeEmptyChange: true
    maskValue: false # Mask sensitive values in the report
    includeNoChange: false
log:
  level: info
  type: out # Log output type can be out or file