database:
  host: localhost
  port: 5050
  name: ccd_data
  username: ccd
  password: ccd
  driver: postgres
  sslmode: disable
  batchSize: 100
  eventDataTable: event_data_report
period:
  startTime: "2024-02-14T15:00:00.000" # considered GMT
  endTime:   "2024-02-14T16:25:00.000" # considered GMT
worker:
  pool: 30
rule:
  active: "staticfieldchange,arrayfieldchange"
scan:
  jurisdiction: BEFTA_JURISDICTION_3
  caseType: BEFTA_CASETYPE_3_2
  caseId:
  maxEventProcessCount: 5000
  batchSize: 100
  concurrent:
    event:
      thresholdMilliseconds: 120000
  fieldChange:
    threshold: 25
  report:
    enabled: true
    includeEmptyChange: true
    maskValue: false
    includeNoChange: false
log:
  level: info
  type: out