database:
  host: localhost
  port: 5050
  name: ccd_data
  username: ccd
  password: ccd
  driver: postgres
  sslmode: require
period:
  startTime: "2022-01-01T07:00:00.000" # considered GMT
  endTime:   "2022-01-31T23:20:59.000"
  searchWindow: 1 # Search results for days
rule:
  active: "samevalueafterchange,fieldchangecount"
scan:
  jurisdiction: DIVORCE
  caseType: NFD
  concurrent:
    event:
      thresholdMilliseconds: 10000 # millisecond
  fieldChange:
    threshold: 25
  report:
    enabled: true
    includeEmptyChange: false
    maskValue: false
log:
  level: info
  type: out